name: Code Analysis
on: [push, pull_request]
jobs:
  clang-format-tidy:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VCPKG_BINARY_SOURCES: clear;nuget,GitHub,readwrite
      VCPKG_DEFAULT_TRIPLET: x64-linux
      FILES: libtvm/*.cpp libtvm/*.hpp*
      FILES_ALL: tvm.spec/*.spec.cpp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Autoconf Macros
        run: sudo apt-get install -y autoconf-archive
      - name: Install Dependencies
        run: sudo apt-get install -y libicu-dev doctest-dev
      - name: Install and update clang tools
        shell: bash
        run: |
          curl "https://apt.llvm.org/llvm.sh" > /tmp/llvm.sh
          sudo bash /tmp/llvm.sh 14
          sudo apt-get install -y clang-format-14 clang-tidy-14
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-14 200
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-14 200
      - name: Run CMake generator
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-format
        run: clang-format ${FILES} ${FILES_ALL} --dry-run -Werror --style=file
        continue-on-error: true
      - name: Run clang-tidy
        run: clang-tidy ${FILES} -p build --warnings-as-errors=*
